% bpmNames = {...
%     'CC.SVBPM0235'...
%     'CC.SVBPM0275'...
%     'CC.SVBPM0365'...
%     'CC.SVBPM0435'...
%     'CC.SVBPI0535'...
%     'CC.SVBPI0645'...
%     'CC.SVBPI0685'...
%     'CC.SVBPI0735'...
%     'CC.SVBPM0845'...
%     'CC.SVBPM0930'...
%     'CB.SVBPM0150'...
%     'CB.SVBPM1030'...
%     'CB.SVBPS0210'...
%     'CB.SVBPS0250'...
%     'CB.SVBPS0310'...
%     'CB.SVBPS0350'...
%     'CB.SVBPS0410'...
%     'CB.SVBPS0450'...
%     'CB.SVBPS0510'...
%     'CB.SVBPS0550'...
%     'CB.SVBPS0610'...
%     'CB.SVBPS0650'...
%     'CB.SVBPS0710'...
%     'CB.SVBPS0750'...
%     'CB.SVBPS0810'...
%     'CB.SVBPS0850'...
%     'CB.SVBPS0910'...
%     'CB.SVBPS0950'...
% };
% 
% horizPos = NaN*ones(length(bpmNames));
% currents = NaN*ones(length(bpmNames));
% 
% for i=1:length(bpmNames)
%     hStr = sprintf('lastDataStruct.%sH.MeanAtCursor.mean.value',bpmNames{i});
%     currStr = sprintf('lastDataStruct.%sS.MeanAtCursor.mean.value',bpmNames{i});
%     
%     horizPos(i) = eval(hStr);
%     currents(i) = eval(currStr);
% end
% 
% subplot(1,2,1); 
% plot(horizPos);
% title('Horizontal Orbit');
% 
% subplot(1,2,2); 
% plot(currents);
% title('Currents');

subplot(1,2,1)
plot(lastDataStruct.CT_SCOPE02_CH04.Acquisition.value.value);
xlim([80 250])
title('SCOPE')
subplot(1,2,2)
plot(lastDataStruct.CT_SVBPM0285H.Samples.samples.value);
title('XENERIC')