function setPhaseShifter(index,value)          
    
    phShiftNames = { ...
       'CT.PHAS-PHM0370',...
       'CC.PHAS-PHM0251',...
       'CB.PHAS-PHM0160'...
    };

    phShiftSetStr = 'Setting#phase';
    
    if (isnan(value))
        warning('Phase Shifter %d (%s) not set: NaN value.',index,phShiftNames{index});
        return;
    else
        matlabJapc.staticSetSignal(...
            obj.cycleName,...
            sprintf('%s/%s',phShiftNames{index},phShiftSetStr),...
            value...
        );
    end
end
