close all;

% figure;
% for ds=1:nDataSets   
%         plot(data{ds}.stdSampleMixBaseSt(1,:));
%         hold all;
%         plot(data{ds}.stdSampleMixBaseSt(2,:));
% end
% title('Baseline noise before pulse: Jitter')
% legLab = {... % For plot legends
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix2',...  
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix3',...
%     'Nominal: Mon1Mix2',... 
%     'Nominal: Mon2Mix3',... 
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix2',...
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix3',...
%     'Split Mon1: Mix2'...  
%     'Split Mon1: Mix3'...  
% };
% legend(legLab)

figure;
for ds=1:nDataSets   
        plot(data{ds}.meanSampleMixBaseSt(1,:));
        hold all;
        plot(data{ds}.meanSampleMixBaseSt(2,:));
end
title('Baseline noise before pulse: Mean')
legLab = {... % For plot legends
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix2',...  
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix3',...
    'Nominal: Mon1Mix2',... 
    'Nominal: Mon2Mix3',... 
    'Split Mon1: Mix1',...
    'Split Mon1: Mix2',...
    'Split Mon1: Mix1',...
    'Split Mon1: Mix3',...
    'Split Mon1: Mix2'...  
    'Split Mon1: Mix3'...  
};
legend(legLab)
ylabel('counts')

% figure;
% for ds=1:nDataSets   
%         plot(data{ds}.stdSampleMixBaseEn(1,:));
%         hold all;
%         plot(data{ds}.stdSampleMixBaseEn(2,:));
% end
% title('Baseline noise after pulse: Jitter')
% legLab = {... % For plot legends
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix2',...  
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix3',...
%     'Nominal: Mon1Mix2',... 
%     'Nominal: Mon2Mix3',... 
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix2',...
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix3',...
%     'Split Mon1: Mix2'...  
%     'Split Mon1: Mix3'...  
% };
% legend(legLab)

figure;
for ds=1:nDataSets   
        plot(data{ds}.meanSampleMixBaseEn(1,:));
        hold all;
        plot(data{ds}.meanSampleMixBaseEn(2,:));
end
title('Baseline noise after pulse: Mean')
legLab = {... % For plot legends
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix2',...  
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix3',...
    'Nominal: Mon1Mix2',... 
    'Nominal: Mon2Mix3',... 
    'Split Mon1: Mix1',...
    'Split Mon1: Mix2',...
    'Split Mon1: Mix1',...
    'Split Mon1: Mix3',...
    'Split Mon1: Mix2'...  
    'Split Mon1: Mix3'...  
};
legend(legLab)
ylabel('counts')
%%
figure;
for ds=1:nDataSets   
        plot(data{ds}.stdSamplePhBaseSt(1,:));
        hold all;
        plot(data{ds}.stdSamplePhBaseSt(2,:));
end
title('Baseline noise before pulse: Jitter')
legLab = {... % For plot legends
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix2',...  
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix3',...
    'Nominal: Mon1Mix2',... 
    'Nominal: Mon2Mix3',... 
    'Split Mon1: Mix1',...
    'Split Mon1: Mix2',...
    'Split Mon1: Mix1',...
    'Split Mon1: Mix3',...
    'Split Mon1: Mix2'...  
    'Split Mon1: Mix3'...  
};
legend(legLab)
ylabel('phase [degrees]')

% figure;
% for ds=1:nDataSets   
%         plot(data{ds}.meanSamplePhBaseSt(1,:));
%         hold all;
%         plot(data{ds}.meanSamplePhBaseSt(2,:));
% end
% title('Baseline noise before pulse: Mean')
% legLab = {... % For plot legends
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix2',...  
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix3',...
%     'Nominal: Mon1Mix2',... 
%     'Nominal: Mon2Mix3',... 
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix2',...
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix3',...
%     'Split Mon1: Mix2'...  
%     'Split Mon1: Mix3'...  
% };
% legend(legLab)
% ylabel('phase [degrees]')

figure;
for ds=1:nDataSets   
        plot(data{ds}.stdSamplePhBaseEn(1,:));
        hold all;
        plot(data{ds}.stdSamplePhBaseEn(2,:));
end
title('Baseline noise after pulse: Jitter')
legLab = {... % For plot legends
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix2',...  
    'Nominal: Mon1Mix1',...
    'Nominal: Mon2Mix3',...
    'Nominal: Mon1Mix2',... 
    'Nominal: Mon2Mix3',... 
    'Split Mon1: Mix1',...
    'Split Mon1: Mix2',...
    'Split Mon1: Mix1',...
    'Split Mon1: Mix3',...
    'Split Mon1: Mix2'...  
    'Split Mon1: Mix3'...  
};
legend(legLab)
ylabel('phase [degrees]')

% figure;
% for ds=1:nDataSets   
%         plot(data{ds}.meanSamplePhBaseEn(1,:));
%         hold all;
%         plot(data{ds}.meanSamplePhBaseEn(2,:));
% end
% title('Baseline noise after pulse: Mean')
% legLab = {... % For plot legends
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix2',...  
%     'Nominal: Mon1Mix1',...
%     'Nominal: Mon2Mix3',...
%     'Nominal: Mon1Mix2',... 
%     'Nominal: Mon2Mix3',... 
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix2',...
%     'Split Mon1: Mix1',...
%     'Split Mon1: Mix3',...
%     'Split Mon1: Mix2'...  
%     'Split Mon1: Mix3'...  
% };
% legend(legLab)
% ylabel('phase [degrees]')
